"""create fbgroups table

Revision ID: 36bea284dc4a
Revises: 
Create Date: 2026-03-11 15:47:11.037257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36bea284dc4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fbgroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=False),
    sa.Column('last_liked_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fbgroups_facebook'), 'fbgroups', ['facebook'], unique=True)
    op.create_index(op.f('ix_fbgroups_id'), 'fbgroups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fbgroups_id'), table_name='fbgroups')
    op.drop_index(op.f('ix_fbgroups_facebook'), table_name='fbgroups')
    op.drop_table('fbgroups')
    # ### end Alembic commands ###
