"""add last_marketed_date

Revision ID: 52a5d241e5cc
Revises: 36bea284dc4a
Create Date: 2026-03-11 15:49:02.282080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a5d241e5cc'
down_revision: Union[str, Sequence[str], None] = '36bea284dc4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fbgroups', sa.Column('last_marketed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fbgroups', 'last_marketed_date')
    # ### end Alembic commands ###
