"""Add posted_articles table

Revision ID: a520a1283c4a
Revises: 52a5d241e5cc
Create Date: 2026-03-11 16:22:15.823252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a520a1283c4a'
down_revision: Union[str, Sequence[str], None] = '52a5d241e5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posted_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posted_articles_id'), 'posted_articles', ['id'], unique=False)
    op.create_index(op.f('ix_posted_articles_url'), 'posted_articles', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posted_articles_url'), table_name='posted_articles')
    op.drop_index(op.f('ix_posted_articles_id'), table_name='posted_articles')
    op.drop_table('posted_articles')
    # ### end Alembic commands ###
