"""add_fb_friends_table

Revision ID: b032c85c242c
Revises: a520a1283c4a
Create Date: 2026-03-14 14:14:39.871816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b032c85c242c'
down_revision: Union[str, Sequence[str], None] = 'a520a1283c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fb_friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('last_messaged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fb_friends_id'), 'fb_friends', ['id'], unique=False)
    op.create_index(op.f('ix_fb_friends_profile_url'), 'fb_friends', ['profile_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_runs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('run_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('scheduler_runs_pkey')),
    sa.UniqueConstraint('run_key', name=op.f('scheduler_runs_run_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('liked_tweets',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tweet_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tweet_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('article_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('liked_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('liked_tweets_pkey')),
    sa.UniqueConstraint('tweet_id', name=op.f('liked_tweets_tweet_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tweet_jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('draft_primary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('draft_alternative', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('thread_opener', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('posted_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('x_post_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('tweet_jobs_article_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tweet_jobs_pkey')),
    sa.UniqueConstraint('article_id', 'draft_primary', 'draft_alternative', name=op.f('tweet_jobs_article_id_draft_primary_draft_alternative_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('articles',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('published_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text_excerpt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('body_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('body_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_judicial_exam_related', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('matched_keywords', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=False),
    sa.Column('first_seen_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_processed_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_tweeted_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tweet_status', sa.TEXT(), server_default=sa.text("'unprocessed'::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('articles_pkey')),
    sa.UniqueConstraint('url', name=op.f('articles_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_fb_friends_profile_url'), table_name='fb_friends')
    op.drop_index(op.f('ix_fb_friends_id'), table_name='fb_friends')
    op.drop_table('fb_friends')
    # ### end Alembic commands ###
